In [1]:
#Importing Libraries
# please do go through this python notebook: 
import warnings
warnings.filterwarnings("ignore")

import csv
import pandas as pd#pandas to create small dataframes 
import datetime #Convert to unix time
import time #Convert to unix time
# if numpy is not installed already : pip3 install numpy
import numpy as np#Do aritmetic operations on arrays
# matplotlib: used to plot graphs
import matplotlib
import matplotlib.pylab as plt
import seaborn as sns#Plots
from matplotlib import rcParams#Size of plots  
from sklearn.cluster import MiniBatchKMeans, KMeans#Clustering
import math
import pickle
import os
# to install xgboost: pip3 install xgboost
import xgboost as xgb

import warnings
import networkx as nx
import pdb
import pickle
from pandas import HDFStore,DataFrame
from pandas import read_hdf
from scipy.sparse.linalg import svds, eigs
import gc
from tqdm import tqdm
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score

In [2]:
from sklearn.tree import DecisionTreeClassifier

In [4]:
df = pd.read_csv('train_data_with_jacard_corrected.csv')
df

,Form,To,Target,src_Indegree,src_Outdegree,Jaccard_Coefficient,follow_back,weight_in,weight_out,weight_f1,weight_f2,weight_f3,weight_f4
0,4862306,3513873,1,291,7998,0.000242,0,0.288675,0.011181,0.299856,0.003228,0.588531,0.311037
1,629760,4763045,1,144,1351,0.007988,0,0.204124,0.027196,0.231321,0.005551,0.435445,0.258517
2,3086336,1009858,1,152,2395,0.007997,0,0.103142,0.020429,0.123572,0.002107,0.226714,0.144001
3,1090555,4388892,1,50,295,0.000000,0,0.301511,0.058124,0.359635,0.017525,0.661147,0.417759
4,307789,4761599,1,161,664,0.061415,0,0.097590,0.038778,0.136368,0.003784,0.233958,0.175147
...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,3768869,3632227,0,23,991,0.000000,0,0.204124,0.031750,0.235874,0.006481,0.439998,0.267624
199996,193463,395062,0,255,7999,0.000000,0,0.707107,0.011180,0.718287,0.007906,1.425394,0.729467
199997,1131409,4535736,0,50,1208,0.000000,0,0.707107,0.028760,0.735867,0.020336,1.442973,0.764627
199998,597722,2395573,0,2,6,0.000000,0,0.179605,0.377964,0.557570,0.067884,0.737175,0.935534
199999,795081,988627,0,161,1738,0.000566,0,0.223607,0.023980,0.247587,0.005362,0.471194,0.271567

In [5]:
X = df[['Form', 'To','src_Indegree','src_Outdegree','Jaccard_Coefficient','follow_back','weight_in','weight_out','weight_f1','weight_f2','weight_f3','weight_f4']]
y = df['Target']

y

0         1
1         1
2         1
3         1
4         1
         ..
199995    0
199996    0
199997    0
199998    0
199999    0
Name: Target, Length: 200000, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
tree_classifier = DecisionTreeClassifier()

In [9]:
tree_classifier.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:
y_pred = tree_classifier.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.858375

In [13]:
tf = pd.read_csv('kaggle_test_data_with_jacard_crrt.csv')
tf

,Form,To,src_Indegree,src_Outdegree,Jaccard_Coefficient,follow_back,weight_in,weight_out,weight_f1,weight_f2,weight_f3,weight_f4
0,3360982,4457271,102,1964,0.036222,0,0.110432,0.022559,0.132990,0.002491,0.243422,0.155549
1,4761876,4698439,68,123,0.000000,0,0.288675,0.089803,0.378478,0.025924,0.667153,0.468280
2,4198430,3615486,217,6996,0.000000,0,0.200000,0.011955,0.211955,0.002391,0.411955,0.223910
3,2945770,747948,210,289,0.004264,0,0.134840,0.058722,0.193562,0.007918,0.328402,0.252284
4,3950088,3360335,149,1309,0.021918,0,0.084515,0.027629,0.112144,0.002335,0.196660,0.139773
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,3116985,2415415,105,449,0.014035,0,0.038925,0.047140,0.086065,0.001835,0.124990,0.133206
1996,265459,842701,95,3947,0.003521,0,0.068519,0.015915,0.084434,0.001090,0.152953,0.100349
1997,2547139,4332939,48,131,0.034247,0,0.288675,0.087039,0.375714,0.025126,0.664389,0.462753
1998,2366264,1815056,10,107,0.008850,0,0.500000,0.096225,0.596225,0.048113,1.096225,0.692450
1999,2735577,1232247,17,544,0.000000,0,0.316228,0.042835,0.359063,0.013546,0.675291,0.401898

In [14]:
y_test_pred = tree_classifier.predict(tf)
y_test_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [15]:
arr = np.array(y_test_pred)
zero_count = np.count_nonzero(arr == 0)
print(zero_count)

726

In [16]:
tf['Predictions'] = arr
tf

,Form,To,src_Indegree,src_Outdegree,Jaccard_Coefficient,follow_back,weight_in,weight_out,weight_f1,weight_f2,weight_f3,weight_f4,Predictions
0,3360982,4457271,102,1964,0.036222,0,0.110432,0.022559,0.132990,0.002491,0.243422,0.155549,1
1,4761876,4698439,68,123,0.000000,0,0.288675,0.089803,0.378478,0.025924,0.667153,0.468280,0
2,4198430,3615486,217,6996,0.000000,0,0.200000,0.011955,0.211955,0.002391,0.411955,0.223910,1
3,2945770,747948,210,289,0.004264,0,0.134840,0.058722,0.193562,0.007918,0.328402,0.252284,1
4,3950088,3360335,149,1309,0.021918,0,0.084515,0.027629,0.112144,0.002335,0.196660,0.139773,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,3116985,2415415,105,449,0.014035,0,0.038925,0.047140,0.086065,0.001835,0.124990,0.133206,1
1996,265459,842701,95,3947,0.003521,0,0.068519,0.015915,0.084434,0.001090,0.152953,0.100349,1
1997,2547139,4332939,48,131,0.034247,0,0.288675,0.087039,0.375714,0.025126,0.664389,0.462753,1
1998,2366264,1815056,10,107,0.008850,0,0.500000,0.096225,0.596225,0.048113,1.096225,0.692450,0
1999,2735577,1232247,17,544,0.000000,0,0.316228,0.042835,0.359063,0.013546,0.675291,0.401898,1

In [17]:
tf['Id'] = range(1, 2001)
tf

,Form,To,src_Indegree,src_Outdegree,Jaccard_Coefficient,follow_back,weight_in,weight_out,weight_f1,weight_f2,weight_f3,weight_f4,Predictions,Id
0,3360982,4457271,102,1964,0.036222,0,0.110432,0.022559,0.132990,0.002491,0.243422,0.155549,1,1
1,4761876,4698439,68,123,0.000000,0,0.288675,0.089803,0.378478,0.025924,0.667153,0.468280,0,2
2,4198430,3615486,217,6996,0.000000,0,0.200000,0.011955,0.211955,0.002391,0.411955,0.223910,1,3
3,2945770,747948,210,289,0.004264,0,0.134840,0.058722,0.193562,0.007918,0.328402,0.252284,1,4
4,3950088,3360335,149,1309,0.021918,0,0.084515,0.027629,0.112144,0.002335,0.196660,0.139773,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,3116985,2415415,105,449,0.014035,0,0.038925,0.047140,0.086065,0.001835,0.124990,0.133206,1,1996
1996,265459,842701,95,3947,0.003521,0,0.068519,0.015915,0.084434,0.001090,0.152953,0.100349,1,1997
1997,2547139,4332939,48,131,0.034247,0,0.288675,0.087039,0.375714,0.025126,0.664389,0.462753,1,1998
1998,2366264,1815056,10,107,0.008850,0,0.500000,0.096225,0.596225,0.048113,1.096225,0.692450,0,1999
1999,2735577,1232247,17,544,0.000000,0,0.316228,0.042835,0.359063,0.013546,0.675291,0.401898,1,2000

In [18]:
X = tf[['Id', 'Predictions']]
X

        Id  Predictions
0        1            1
1        2            0
2        3            1
3        4            1
4        5            1
...    ...          ...
1995  1996            1
1996  1997            1
1997  1998            1
1998  1999            0
1999  2000            1

[2000 rows x 2 columns]

In [19]:
csv_file_path = 'up_5_jacrad_crt_02_only_DT.csv'
X.to_csv(csv_file_path, index=False)